# Clase 08 — Exploración Inicial y Visualización Básica

> Notebook de práctica. Ejecutá las celdas a medida que avanzás en el artículo.

¡Bienvenido al equipo de datos de **TechMarket**!

La empresa acaba de finalizar una migración completa de su sistema de ventas hacia una nueva plataforma. Como ocurre en cualquier proyecto de migración, nadie sabe con certeza si toda la información llegó correctamente. Durante este laboratorio realizarás exactamente el mismo proceso que seguiría un analista de datos en una empresa real al recibir un conjunto de datos por primera vez.

Cada misión representa una solicitud realizada por distintos miembros de la empresa. No se espera que conozcas todas las respuestas de memoria. Utiliza las herramientas aprendidas durante la clase para investigar el dataset y tomar decisiones.


## Escenario

La empresa almacena información de sus productos en una base de datos SQLite. El equipo de ingeniería ya realizó la consulta y cargó los datos en un DataFrame llamado `df`.

In [3]:
import sqlite3
import pandas as pd

conexion = sqlite3.connect("ventas.db")

df = pd.read_sql(
    "SELECT * FROM productos",
    conexion
)

A partir de este momento trabajarás únicamente con el DataFrame.

### Ejercicio 1 — ¿Llegaron todos los datos?

Durante la madrugada se ejecutó una consulta SQL para obtener el catálogo completo de productos que actualmente comercializa la empresa. Antes de comenzar cualquier análisis, tu supervisor quiere asegurarse de que la consulta SQL devolvió una cantidad razonable de información.

**Tu tarea**

Determina:

- ¿Cuántos registros recibió el DataFrame?
- ¿Cuántas columnas contiene?

In [4]:
# escribe tu código aquí}
print(df.shape)

(250, 5)

> **Pregunta para reflexionar**

¿Por qué verificar el tamaño del dataset debería ser una de las primeras tareas de cualquier analista de datos?

### Ejercicio 2 — Primera inspección visual

Ahora debes comprobar rápidamente que los datos realmente representan productos. Muchas veces una consulta SQL devuelve columnas equivocadas, datos mezclados o incluso tablas incorrectas.

**Consigna:** Realiza una inspección visual del DataFrame y observa:

- nombres de columnas
- primeras filas
- si los datos parecen coherentes

In [5]:
# Código de ejemplo
df.columns
df.head()
df.head()

#si los datos Son coherentes.

   id       nombre categoria     precio  stock
0   1  Mouse Gamer    gaming  260318.02     31
1   2      Headset    gaming   33167.77     54
2   3     Notebook      tech  197752.04     91
3   4  Auriculares      tech  283872.37      0
4   5   Biblioteca   muebles   56951.39     97

> **Piensa como analista**

¿Detectas algo que te haga desconfiar del dataset?

### Ejercicio 3 — Revisando el final de la carga

Durante algunas migraciones los últimos registros pueden quedar incompletos debido a interrupciones durante la exportación.

**Consigna:** Inspecciona las últimas filas del DataFrame. Busca posibles señales de problemas como:

- registros incompletos;#no se observan datos faltantes
- valores vacíos;
- datos extraños.

In [6]:
# ultima filas del df
print(df.tail())

      id            nombre   categoria     precio  stock
245  246           Monitor        tech  105639.86    100
246  247        Archivador     oficina   16098.38     43
247  248     Teclado Gamer      gaming   59299.78    106
248  249  Soporte Notebook  accesorios   18161.27     46
249  250        Biblioteca     muebles  264079.73    100

### Ejercicio 4 — ¿Qué tipo de información recibimos?

Antes de realizar cálculos necesitas conocer qué representa cada columna. No tendría sentido calcular promedios sobre texto ni contar frecuencias de valores numéricos sin comprender su significado.

**Consigna:** Obtén un resumen de la estructura del DataFrame e identifica:

- nombres de columnas;
- tipos de datos;
- cantidad de valores no nulos.

In [7]:
# tu codigo aquí
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         250 non-null    int64
 1   nombre     250 non-null    str
 2   categoria  248 non-null    str
 3   precio     246 non-null    float64
 4   stock      250 non-null    int64
dtypes: float64(1), int64(2), str(2)
memory usage: 9.9 KB

> **Pregunta para reflexionar**

¿Por qué resulta peligroso asumir el tipo de una columna sin verificarlo?

### Ejercicio 5 — Buscando valores sospechosos

El gerente financiero cree que algunos productos podrían haberse cargado con precios incorrectos. No quiere revisar miles de registros manualmente.

**Consigna:** Realiza una exploración estadística de las columnas numéricas e intenta responder:

- ¿Cuál es el precio mínimo?
- ¿Cuál es el máximo?
- ¿El promedio parece razonable?
- ¿Observas algún valor que llame la atención?

In [8]:
# -Resumen rapido 
df.describe()

               id        precio       stock
count  250.000000  2.460000e+02  250.000000
mean   125.500000  1.892422e+05   59.024000
std     72.312977  1.792635e+05   35.311571
min      1.000000  4.230350e+03   -2.000000
25%     63.250000  9.113853e+04   28.000000
50%    125.500000  1.849493e+05   60.000000
75%    187.750000  2.700179e+05   91.750000
max    250.000000  2.500000e+06  120.000000

### Ejercicio 6 — Entendiendo el catálogo

El director comercial quiere conocer cómo está distribuido el catálogo de productos.

**Consigna:** Genera un resumen que responda:

- ¿Cuántos productos existen por categoría?
- ¿Cuál es la categoría más grande?
- ¿Cuál es la menos representada?

In [9]:
# tu codigo aquí
df["categoria"].value_counts()

# Categoria  Mas grande tech 90
# Menos representada accesorios 26

categoria
tech          90
muebles       57
gaming        40
oficina       35
accesorios    26
Name: count, dtype: int64

### Ejercicio 7 — ¿Qué porcentaje representa cada categoría?

Las cantidades son útiles, pero la dirección prefiere trabajar con porcentajes.

**Consigna:** Calcula qué porcentaje del catálogo pertenece a cada categoría.

In [10]:
# porcentaje por categoria
df["categoria"].value_counts(normalize=True)

categoria
tech          0.362903
muebles       0.229839
gaming        0.161290
oficina       0.141129
accesorios    0.104839
Name: proportion, dtype: float64

> **Pregunta para reflexionar**

¿Por qué los porcentajes suelen ser más útiles que los valores absolutos cuando se comparan empresas de distintos tamaños?

### Ejercicio 8 — Preparando una reunión ejecutiva

Mañana habrá una reunión con la dirección y nadie quiere leer una tabla con números.

**Consigna:** Construye un gráfico de barras que permita visualizar rápidamente la cantidad de productos por categoría.

In [1]:
# tu codigo aquí
import pandas as pd
import matplotlib.pyplot as plt

# The 'r' before the quotes is super important for Windows paths!
df = pd.read_csv(r"C:\Users\Giovanni\Downloads\datos.csv") 

df["categoria"].value_counts().plot(kind="bar")
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Giovanni\\Downloads\\datos.csv'

In [2]:
import os

downloads_path = r"C:\Users\Giovanni\Downloads"
files = [f for f in os.listdir(downloads_path) if f.lower().startswith("datos")]
print("Files found:", files)

Files found: []

In [4]:
import tkinter as tk
from tkinter import filedialog

# Open a window to browse for your file
root = tk.Tk()
root.withdraw() # Hide the main small window
root.attributes('-topmost', True) # Bring the file dialog to the front

real_path = filedialog.askopenfilename(title="Select your dataset file")
print("Your real file path is:\n", real_path)

Your real file path is:

In [14]:
import sys
!{sys.executable} -m pip install matplotlib

Collecting matplotlib
  Downloading matplotlib-3.11.0-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.25 in c:\users\giovanni\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from matplotlib) (2.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\giovanni\appdata\roaming\python\python314\site-packages (from matplotlib) (26.2)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\giovanni\appdata\roaming\python\python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\giovanni\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.11.0-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ------- -------------------------------- 1.8/9.5 MB 9.8 MB/s eta 0:00:01
   ---------------- ----------------------- 3.9/9.5 MB 10.1 MB/s eta 0:00:01
   --------------------------- ------------ 6.6/9.5 MB 11.1 MB/s eta 0:00:01
   ---------------------------------- ----- 8.1/9.5 MB 11.0 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 10.5 MB/s  0:00:00
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 12.1 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------- ----------------------------- 1.8/7.2 MB 13.0 MB/s eta 0:00:01
   ------------------------ --------------- 4.5/7.2 MB 12.3 MB/s eta 0:00:01
   ------------------------------- -------- 5.8/7.2 MB 12.2 MB/s eta 0:00:01
   ---------------------------------------- 7.2/7.2 MB 11.3 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib

   ---------------------------------------- 0/7 [pyparsing]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----- ---------------------------------- 1/7 [pillow]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ----------------- ---------------------- 3/7 [fonttools]
   ---------------------------- ----------- 5/7 [contourpy]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------- ----- 6/7 [matplotlib]
   ---------------------------------------- 7/7 [matplotlib]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.11.0 pillow-12.3.0 pyparsing-3.3.2

  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\Giovanni\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### Ejercicio 9 — Un gráfico listo para presentar


El gráfico anterior será incorporado a un informe ejecutivo. Debe poder entenderse sin necesidad de explicaciones adicionales.

**Consigna:** Mejora el gráfico agregando:

- título;
- nombre del eje X;
- nombre del eje Y.

In [ ]:
# tu codigo aquí

### Ejercicio 10 — Tu primer informe de exploración

Has terminado la revisión inicial del dataset.Antes de entregarlo al resto del equipo debes elaborar un pequeño informe técnico.

**Consigna:** Responde las siguientes preguntas utilizando toda la información obtenida durante las misiones anteriores.

1. ¿Cuántos registros contiene el dataset?

2. ¿Cuántas variables fueron recibidas?

3. ¿Existen columnas con datos faltantes?

4. ¿Qué tipos de datos predominan?

5. ¿Cuál es la categoría con mayor cantidad de productos?

6. ¿Observaste valores que podrían requerir una limpieza posterior?

7. ¿Consideras que el dataset está listo para comenzar un análisis más profundo? Justifica tu respuesta.

In [ ]:
# responde a las preguntas acá