In [1]:
import sqlite3

conexion = sqlite3.connect("ventas.db")
cursor = conexion.cursor()

cursor.execute("""
    CREATE TABLE IF NOT EXISTS productos (
        id INTEGER PRIMARY KEY,
        nombre TEXT,
        categoria TEXT,
        precio REAL,
        stock INTEGER
    )
""")

cursor.executemany("""
    INSERT INTO productos (nombre, categoria, precio, stock)
    VALUES (?, ?, ?, ?)
""", [
    ("Notebook",    "tech",    320000, 5),
    ("Mouse",       "tech",    8500,   42),
    ("Escritorio",  "muebles", 85000,  3),
    ("Silla",       "muebles", 45000,  8),
    ("Monitor",     "tech",    210000, 0),
    ("Auriculares", "tech",    32000,  18),
    ("Lámpara",     "muebles", 12000,  25),
])

conexion.commit()

# Consultas sql + pandas

In [5]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-macosx_11_0_arm64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 4.0 MB/s eta 0:00:00
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/rosinni/Library/Python/3.12/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/rosinni/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-3.0.3-cp312-cp312-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 44.7 MB/s eta 0:00:00a 0:00:01
Downloading numpy-2.5.1-cp312-cp312-macosx_14_0_arm64.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 42.3 MB/s eta 0:00:0000:0100:01
Installing collected packages: numpy, pandas
Successfully installed numpy-2.5.1 pandas-3.0.3

[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd

tablas = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table'",
    conexion
)

tablas

        name
0  productos

In [10]:
estructura = pd.read_sql(
    "PRAGMA table_info(productos)",
    conexion
)

estructura

   cid       name     type  notnull dflt_value  pk
0    0         id  INTEGER        0       None   1
1    1     nombre     TEXT        0       None   0
2    2  categoria     TEXT        0       None   0
3    3     precio     REAL        0       None   0
4    4      stock  INTEGER        0       None   0

In [11]:
df = pd.read_sql(
    "SELECT * FROM productos",
    conexion
)

df

   id       nombre categoria    precio  stock
0   1     Notebook      tech  320000.0      5
1   2        Mouse      tech    8500.0     42
2   3   Escritorio   muebles   85000.0      3
3   4        Silla   muebles   45000.0      8
4   5      Monitor      tech  210000.0      0
5   6  Auriculares      tech   32000.0     18
6   7      Lámpara   muebles   12000.0     25